version: "3.7"
services:
  seckill-consul:
    image: consul
    environment:
      - "CONSUL_BIND_INTERFACE=eth0"
    container_name: seckill-consul
    ports:
      - 8500:8500
    expose: 
      - "8500"
    networks:
      seckill:
        aliases:
          - "seckillconsul"
  seckill-redis:
    image: redis
    container_name: seckill-redis
    ports:
      - 6379:6379
    expose:
      - "6379"
    networks:
      seckill:
        aliases:
          - "seckillredis"
  seckill-mysql:
    image: mysql
    container_name: seckill-mysql
    ports:
      - 3307:3306
    expose:
      - "3306"
    environment:
      - "MYSQL_DATABASE=sk-admin"
      - "MYSQL_ROOT_PASSWORD=0925824166"
    networks:
      seckill:
        aliases:
          - "seckillmysql"
  seckill-rabbitmq:
    image: rabbitmq:management
    container_name: seckill-rabbitmq
    ports:
      - 15672:15672
    expose:
      - "5672"
    environment:
      - "RABBITMQ_DEFAULT_USER=lijie"
      - "RABBITMQ_DEFAULT_PASS=824166"
    networks:
      seckill:
        aliases:
          - "seckillrabbitmq"
  # spring-cloud-config-server
  seckill-spring-config-server:
    image: sdglbl/sccs-consul-rabbitmq
    container_name: seckill-spring-config-serve
    ports:
      - 8888:8888
    environment:
      - "SPRING_PROFILES_ACTIVE=cloud-bus-rabbit"
    volumes:
      - "./config/:/config"
    networks:
      seckill:
        aliases:
          - "seckillscs"
    depends_on:
      - seckill-rabbitmq
      - seckill-consul
  # kong gataway
  seckill-kong:
    image: kong:latest
    container_name: seckill-kong
    # command: ["kong","migrations","bootstrap","&","kong","migrations","up"]
    environment:
      - "KONG_DATABASE=postgres"
      - "KONG_PG_HOST=kong-database"
      - "KONG_PG_PASSWORD=kong"
      - "KONG_CASSANDRA_CONTACT_POINTS=kong-database"
      - "KONG_PROXY_ACCESS_LOG=/dev/stdout"
      - "KONG_ADMIN_ACCESS_LOG=/dev/stdout"
      - "KONG_PROXY_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_LISTEN=0.0.0.0:8001,0.0.0.0:8444 ssl"
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    networks:
      seckill:
        aliases:
          - "seckillkong"
    depends_on:
      - kong-database
  seckill-konga:
    image: pantsel/konga
    container_name: seckill-konga
    environment:
      - "TOKEN_SECRET=blueskykong.com"
      - "NODE_ENV=production"
    ports:
      - 8080:1337
    networks:
      seckill:
        aliases:
          - "seckillkonga"
    depends_on:
      - kong-database
  kong-database:
    image: postgres:latest
    container_name: kong-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    networks:
      seckill:
        aliases:
          - "kong-database"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/lijie/postgresql:/var/lib/postgresql/data
  
  
networks:
  seckill:
    external: true
