server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    consul:
      discovery:
        preferIpAddress: true
        enabled: true
        register: true
        service-name: config-service
        health-check-interval: 10s
        health-check-timeout: 20s
        heartbeat:
          enabled: true
        ip-address: seckill-sccs
        port: ${server.port}
        lifecycle:
          enabled: true
        scheme: http
        prefer-agent-address: false
        register-health-check: true
        tags: master
        query-passing: true
      retry:
        initial-interval: 1000
        max-attempts: 4
        max-interval: 1000
      host: seckillconsul
      port: 8500

---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SDGLBL/config-repo
          searchPaths: dev
          username: sdglbl
          password: 824166ChAo0925
          force-pull: true
  rabbitmq:
    host: seckillrabbitmq
    port: 5672
    username: lijie
    password: 824166

management:
  endpoints:
    web:
      exposure:
        include: '*'